module.exports = {
    Index: require("./agindex"),
    Ag: require("./ag"),
    AgOfList: require("./agOfList"),
    Aktie: require("./aktie"),
    Aktionaer: require("./aktionaer"),
    Anleihe: require("./anleihe"),
    Bilanz: require("./bilanz"),
    Ceo: require("./ceo"),
    Chronik: require("./chronik"),
    Ke: require("./ke"),
    Kh: require("./kh"),
    Kontoauszug: require("./kontoauszug"),
    Kredit: require("./kredit"),
    Namenswechsel: require("./namechange"),
    Order: require("./order"),
    Uebernahme: require("./uebernahme"),
    Zertifikat: require("./zertifikat"),
};